# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


  
# Box Settings
  config.vm.box = "ubuntu/bionic64"
  
# Mentioning the SSH Username/Password:
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

# Begin Configuring
  config.vm.define "lamp" do|lamp|

  #Provider Settings
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 6144
  vb.cpus = 3
	   
# config.vm.box_check_update = false

sudo apt update
sudo apt install apache2

# Network Settings
   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
   config.vm.network "private_network", ip: "192.168.33.10"
   
   config.vm.provision "shell", path: "bootstrap.sh" 
   
   
# Folder Settings
  config.vm.synced_folder ".", "/var/www/html", :nfs => { :mount_options => ["dmode=777", "fmode=666"] }  
 
 
   
  
end
